apiVersion: v1
kind: Service
metadata:
  name: arch-builder-frontend-svc
spec:
  selector:
    app: arch-builder-frontend
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: arch-builder-backend-svc
spec:
  selector:
    app: arch-builder-backend
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP